# Generated by Django 4.2 on 2024-03-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_g', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.AlterField(
            model_name='profesor',
            name='apellido',
            field=models.CharField(max_length=20),
        ),
    ]
