# Generated by Django 4.2 on 2024-03-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_g', '0003_celular_delete_curso_delete_estudiante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='celular',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
