# Generated by Django 4.2 on 2024-03-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_g', '0004_celular_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='celular',
            name='estado',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
