# Generated by Django 4.2 on 2024-03-08 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_g', '0006_celular_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celular',
            name='imagen',
            field=models.ImageField(null=True, upload_to='celulares/'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Ingrese un comentario', max_length=1000)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_g.celular')),
            ],
            options={
                'ordering': ['-post_date'],
            },
        ),
    ]
