# Generated by Django 4.2 on 2024-03-09 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_g', '0008_celularnuevo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celularnuevo',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='celularnuevo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='celularesNuevos/'),
        ),
    ]
