# Generated by Django 4.2 on 2024-03-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_g', '0009_remove_celularnuevo_nombre_alter_celularnuevo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='celularnuevo',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='celularnuevo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='celulares/'),
        ),
    ]
